#!/usr/bin/env bash # for helix syntax highlighting

# # class                 border  bground text    indicator child_border
# set $nofocusbg #e4ddd2
# set $nofocusfg #605a52
# set $focusfg #605a52
# set $focusbg #f7f3ee
# set focusinfg
# client.focused          $focusbg $focusbg $focusfg $focusbg $focusbg
# client.focused_inactive #44475A #44475A #BFBFBF #44475A   #44475A
# client.unfocused        $nofocusbg $nofocusbg #bfbfbf $nofocusbg   $nofocusbg
# client.urgent           #50fa7b #44475a #50fa7b #FF5555   #FF5555
# client.placeholder      #282A36 #282A36 #F8F8F2 #282A36   #282A36
# class                 border  bground text    indicator child_border
client.focused          #44475A #6272a4 #F8F8F2 #44475A   #44475A
client.focused_inactive #44475A #44475A #BFBFBF #44475A   #44475A
client.unfocused        #282A36 #282A36 #BFBFBF #282A36   #282A36
client.urgent           #50fa7b #44475a #50fa7b #FF5555   #FF5555
client.placeholder      #282A36 #282A36 #F8F8F2 #282A36   #282A36

bar {
    mode invisible
}
