#!/usr/bin/env bash # for helix syntax highlighting

include outputs
include inputs
include windows
include colors
include startup

set $mod Mod4

set $left Left
set $down Down
set $up Up
set $right Right

set $font pango:Jost
set $weight Light
set $size 13

font $font $size

# default_border none
focus_follows_mouse no
workspace_auto_back_and_forth yes
title_align center
workspace_layout tabbed
# hide_edge_borders --i3 smart
hide_edge_borders smart
# mouse_warping none

floating_modifier $mod normal
focus_on_window_activation focus

titlebar_border_thickness 0
titlebar_padding 5 0

# split window so that remarkable tablet has full range
bindsym $mod+Ctrl+Shift+F3 exec swaymsg "splith, exec wezterm start --class wezterm-600px"

bindsym $mod+F9 exec ~/scripts/switch-bg.clj new current
bindsym $mod+Ctrl+Shift+F9 exec ~/scripts/switch-bg.clj discard current
bindsym button6 --whole-window focus output next
bindsym button7 --whole-window exec ~/.config/sway/swap-visible-workspaces.sh
# bindsym button7 --whole-window focus output next
bindcode 277 --whole-window move container to output next

# set $term ~/scripts/wezterm-start-on-current-workspace.fish
# set $term wezterm
set $term wezterm
set $otherterm kitty
bindsym $mod+Return exec $term
bindsym $mod+Ctrl+Return exec $otherterm

# Kill focused window
bindsym $mod+q kill

# Start your launcher
set $menu "rofi -show-icons -combi-modi window#drun -show combi"
bindsym $mod+d exec $menu
# bindsym $mod+o exec $menu
bindsym $mod+u [urgent=first] focus

bindsym $mod+e exec ~/scripts/open-emacs-or-focus-wayland.clj
# Reload the configuration file
bindsym $mod+F5 reload

bindsym $mod+F8 opacity 1
# bindsym $mod+Control+F8 opacity $opacity

bindsym $mod+Shift+Control+e exec swaymsg exit

bindsym button2 kill
# bindsym BTN_MIDDLE kill
bindsym button3 move container to output left

bindsym $mod+$left focus left
bindsym $mod+$down focus down
bindsym $mod+$up focus up
bindsym $mod+$right focus right

bindsym $mod+n focus left
# bindsym $mod+e focus down
bindsym $mod+i focus up
bindsym $mod+o focus right

bindsym $mod+Shift+$left move left
bindsym $mod+Shift+$down move down
bindsym $mod+Shift+$up move up
bindsym $mod+Shift+$right move right

bindsym $mod+Shift+n move left
bindsym $mod+Shift+e move down
bindsym $mod+Shift+i move up
bindsym $mod+Shift+o move right

bindsym $mod+Shift+h splith
bindsym $mod+Shift+v splitv

# bindsym $mod+s layout stacking
bindsym $mod+Control+t layout tabbed
bindsym $mod+Control+s layout toggle split

bindsym $mod+f fullscreen
bindsym $mod+Control+f border toggle

bindsym $mod+period focus mode_toggle

# focus the parent container
bindsym $mod+Control+c focus parent

# focus the child container
bindsym $mod+c focus child

# move the currently focused window to the scratchpad
# bindsym $mod+Shift+period move scratchpad
bindsym $mod+comma move scratchpad
bindsym $mod+h scratchpad show
# Show the next scratchpad window or hide the focused scratchpad window.
# If there are multiple scratchpad windows, this command cycles through them.
# bindsym $mod+period scratchpad show

bindsym F21 focus right
bindsym F23 focus left

bindsym $mod+Shift+f floating toggle

bindsym $mod+space focus output left

bindsym $mod+Control+space exec ~/scripts/swap-visible-workspaces.clj
bindsym $mod+Shift+space move window to output left

bindsym $mod+a workspace prev_on_output
bindsym $mod+Shift+a move container to workspace next_on_output
bindsym $mod+t workspace next_on_output
bindsym $mod+Shift+t move container to workspace prev_on_output
bindsym $mod+b workspace back_and_forth

bindsym $mod+1 workspace number 1
bindsym $mod+2 workspace number 2
bindsym $mod+3 workspace number 3
bindsym $mod+4 workspace number 4
bindsym $mod+5 workspace number 5
bindsym $mod+6 workspace number 6
bindsym $mod+7 workspace number 7
bindsym $mod+8 workspace number 8
bindsym $mod+9 workspace number 9
bindsym $mod+0 workspace number 10

bindsym $mod+Shift+1 move container to workspace number 1
bindsym $mod+Shift+2 move container to workspace number 2
bindsym $mod+Shift+3 move container to workspace number 3
bindsym $mod+Shift+4 move container to workspace number 4
bindsym $mod+Shift+5 move container to workspace number 5
bindsym $mod+Shift+6 move container to workspace number 6
bindsym $mod+Shift+7 move container to workspace number 7
bindsym $mod+Shift+8 move container to workspace number 8
bindsym $mod+Shift+9 move container to workspace number 9
bindsym $mod+Shift+0 move container to workspace number 10

bindsym $mod+w exec ~/scripts/new-workspace.clj focus
bindsym $mod+Shift+w exec ~/scripts/new-workspace.clj move-to

bindsym XF86AudioRaiseVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ +5%
bindsym XF86AudioLowerVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ -5%
bindsym XF86AudioMute exec --no-startup-id pactl set-sink-mute @DEFAULT_SINK@ toggle

# toggle mic mute
bindsym XF86Mail exec ~/scripts/set-all-sources.clj toggle-mute

# push to talk
bindcode --release --no-repeat 199 exec ~/scripts/set-all-sources.clj mute
bindcode 199 exec ~/scripts/set-all-sources.clj unmute

# select screenshot to clipboard
bindsym $mod+F4 exec grim -g "$(slurp)" - | wl-copy
bindsym $mod+Ctrl+F4 exec ~/scripts/screenshot-with-prompt.fish

# input a filename, select, record the selection, copy filename to clipboard. call again to stop
bindsym $mod+F2 exec ~/scripts/record-selection.fish

# org screenshot
bindsym $mod+F3 exec ~/scripts/org-screenshot.sh

# color picker to clipboard
bindsym $mod+F12 exec grim -g "$(slurp -p)" -t ppm - | convert - -format '%[pixel:p{0,0}]' txt:- | tail -n 1 | cut -d ' ' -f 4 | wl-copy


bindsym $mod+j exec rofimoji --selector wofi --skin-tone neutral

bindsym $mod+F1 exec sh ~/scripts/toggle-work-vpn.sh

include /etc/sway/config.d/*
