# theme = "modus_vivendi_tritanopia"

# theme = "my_modus"
# theme = "my_poimandres"
theme = "my_default"

[editor]
line-number = "relative"
cursorline = true
auto-save = true
color-modes = true
jump-label-alphabet = "ntesirlpfuywdhcxqoa"
completion-trigger-len = 1
soft-wrap.enable = true


statusline.right = [
  "diagnostics",
  "version-control",
  "selections",
  "register",
  "position",
  "position-percentage",
  "file-encoding",
]

cursor-shape.insert = "bar"
cursor-shape.normal = "block"
cursor-shape.select = "underline"

indent-guides.render = true
indent-guides.character = "┆"
indent-guides.skip-levels = 1

lsp.display-inlay-hints = true

file-picker.hidden = false

[editor.whitespace.render]
space = "none"
tab = "none"
nbsp = "none"
nnbsp = "none"
newline = "all"


[editor.whitespace.characters]
newline = "↩"

[keys.insert]
C-q = ":q"
A-x = "command_palette"
C-s = ["commit_undo_checkpoint", ":write"]


# readline bindings
C-a = "goto_first_nonwhitespace"
C-e = ["goto_line_end", "move_char_right"]
A-b = "move_prev_word_start"
A-f = "move_next_word_end"
C-f = "move_char_right"
C-b = "move_char_left"
# default
# Ctrl-w, Alt-Backspace	Delete previous word	delete_word_backward
# Alt-d,  Alt-Delete	Delete next word	delete_word_forward
# Ctrl-u, Delete to start of line	kill_to_line_start
# Ctrl-k, Delete to end of line	kill_to_line_end
[keys.normal]
C-q = ":q"
# A-x = "command_palette"
C-s = ":w"
C-S = "save_selection"
Z.Z = ":x"
G = "goto_file_end"

"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
h = "flip_selections"
l = "goto_word"

[keys.normal.space]
q.q = ":quit"
q.r = ":config-reload"
q.o = ":config-open"
q.f = ":format"

[keys.select]
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
h = "flip_selections"
l = "goto_word"
