# theme = "modus_vivendi_tritanopia"

theme = "my_modus"

editor.soft-wrap.enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "▏"
skip-levels = 1


[editor.lsp]
display-messages = true
display-inlay-hints = true
display-signature-help-docs = true

[editor.file-picker]
hidden = false

[keys.insert]
C-q = ":q"
A-x = "command_palette"
[keys.insert.C-x]
"C-s" = ["commit_undo_checkpoint", ":write"]

[keys.normal]
C-q = ":q"
"ret" = ["open_below", "normal_mode"]
A-x = "command_palette"
[keys.normal.C-x]
"C-s" = ":w"

[keys.normal.Z]
Z = ":x"


