# theme = "modus_vivendi_tritanopia"

theme = "my_modus"

[editor]
line-number = "relative"
cursorline = true
auto-save = true
color-modes = true
jump-label-alphabet = "ntesirlpfuywdhcxqoa"

soft-wrap.enable = true

# statusline.separator = " "
statusline.right = [
  # "workspace-diagnostics",
  "diagnostics",
  "version-control",
  # "separator",
  "selections",
  "register",
  # "separator",
  "position",
  "position-percentage",
  "file-encoding",
  # "separator",
]

cursor-shape.insert = "bar"
cursor-shape.normal = "block"
cursor-shape.select = "underline"

indent-guides.render = true
indent-guides.character = "┆"
indent-guides.skip-levels = 1

# lsp.display-messages = true
lsp.display-inlay-hints = true

file-picker.hidden = false


[keys.insert]
C-q = ":q"
A-x = "command_palette"
C-x.C-s = ["commit_undo_checkpoint", ":write"]

[keys.normal]
C-q = ":q"
# ret = ["open_below", "normal_mode"]
A-x = "command_palette"
C-x.C-s = ":w"
Z.Z = ":x"

"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
h = "flip_selections"
l = "goto_word"

space.c.r = ":config-reload"
space.c.o = ":config-open"

[keys.select]
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
h = "flip_selections"
l = "goto_word"
