# theme = "modus_vivendi_tritanopia"
theme = "my_modus"



[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"


[keys.insert]
C-q = ":q"
A-x = "command_palette"
[keys.insert.C-x]
"C-s" = ["commit_undo_checkpoint", ":w"]

[keys.normal]
C-q = ":q"
"ret" = ["open_below", "normal_mode"]
A-x = "command_palette"
[keys.normal.C-x]
"C-s" = ":w"

[keys.normal.Z]
Z = ":x"
