# theme = "modus_vivendi_tritanopia"

# theme = "my_modus"
theme = "my_poimandres"

[editor]
line-number = "relative"
cursorline = true
auto-save = true
color-modes = true
jump-label-alphabet = "ntesirlpfuywdhcxqoa"
completion-trigger-len = 1
soft-wrap.enable = true


statusline.right = [
  "diagnostics",
  "version-control",
  "selections",
  "register",
  "position",
  "position-percentage",
  "file-encoding",
]

cursor-shape.insert = "bar"
cursor-shape.normal = "block"
cursor-shape.select = "underline"

indent-guides.render = true
indent-guides.character = "┆"
indent-guides.skip-levels = 1

lsp.display-inlay-hints = true

file-picker.hidden = false

[editor.whitespace.render]
space = "none"
tab = "none"
nbsp = "none"
nnbsp = "none"
newline = "all"


[editor.whitespace.characters]
# space = "·"
# nbsp = "⍽"
# nnbsp = "␣"
# tab = "→"
# newline = "⏎"
newline = "↩"
# newline = "↵"
# tabpad = "·" # Tabs will look like "→···" (depending on tab width)# ⌅
# ↩

# newline = "⌤"
# newline = "⌅"
# ⏎↵↵

[keys.insert]
C-q = ":q"
A-x = "command_palette"
C-x.C-s = ["commit_undo_checkpoint", ":write"]

[keys.normal]
C-q = ":q"
A-x = "command_palette"
C-x.C-s = ":w"
Z.Z = ":x"

"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
h = "flip_selections"
l = "goto_word"

[keys.normal.space]
q.q = ":quit"
q.r = ":config-reload"
q.o = ":config-open"

[keys.select]
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
h = "flip_selections"
l = "goto_word"
